// src/main/webapp/app/entities/ingest-event/ingest-event.tsx
import React, { useEffect, useState } from 'react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { Button, Table } from 'reactstrap';
import { TextFormat, Translate, getSortState } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faSort, faSortDown, faSortUp } from '@fortawesome/free-solid-svg-icons';
import { APP_DATE_FORMAT } from 'app/config/constants';
import { ASC, DESC } from 'app/shared/util/pagination.constants';
import { overrideSortStateWithQueryParams } from 'app/shared/util/entity-utils';
import { useAppDispatch, useAppSelector } from 'app/config/store';

import { getEntities } from './ingest-event.reducer';

export const IngestEvent = () => {
  const dispatch = useAppDispatch();

  const pageLocation = useLocation();
  const navigate = useNavigate();

  const [sortState, setSortState] = useState(overrideSortStateWithQueryParams(getSortState(pageLocation, 'id'), pageLocation.search));

  const ingestEventList = useAppSelector(state => state.ingestEvent.entities);
  const loading = useAppSelector(state => state.ingestEvent.loading);

  const getAllEntities = () => {
    dispatch(
      getEntities({
        sort: `${sortState.sort},${sortState.order}`,
      }),
    );
  };

  const sortEntities = () => {
    getAllEntities();
    const endURL = `?sort=${sortState.sort},${sortState.order}`;
    if (pageLocation.search !== endURL) {
      navigate(`${pageLocation.pathname}${endURL}`);
    }
  };

  useEffect(() => {
    sortEntities();
  }, [sortState.order, sortState.sort]);

  const sort = p => () => {
    setSortState({
      ...sortState,
      order: sortState.order === ASC ? DESC : ASC,
      sort: p,
    });
  };

  const handleSyncList = () => {
    sortEntities();
  };

  const getSortIconByFieldName = (fieldName: string) => {
    const sortFieldName = sortState.sort;
    const order = sortState.order;
    if (sortFieldName !== fieldName) {
      return faSort;
    }
    return order === ASC ? faSortUp : faSortDown;
  };

  return (
    <div>
      <h2 id="ingest-event-heading" data-cy="IngestEventHeading">
        <Translate contentKey="booksEtlApp.ingestEvent.home.title">Ingest Events</Translate>
        <div className="d-flex justify-content-end">
          <Button className="me-2" color="info" onClick={handleSyncList} disabled={loading}>
            <FontAwesomeIcon icon="sync" spin={loading} />{' '}
            <Translate contentKey="booksEtlApp.ingestEvent.home.refreshListLabel">Refresh List</Translate>
          </Button>
          <Link to="/ingest-event/new" className="btn btn-primary jh-create-entity" id="jh-create-entity" data-cy="entityCreateButton">
            <FontAwesomeIcon icon="plus" />
            &nbsp;
            <Translate contentKey="booksEtlApp.ingestEvent.home.createLabel">Create new Ingest Event</Translate>
          </Link>
        </div>
      </h2>
      <div className="table-responsive">
        {ingestEventList && ingestEventList.length > 0 ? (
          <Table responsive>
            <thead>
              <tr>
                <th className="hand" onClick={sort('id')}>
                  <Translate contentKey="booksEtlApp.ingestEvent.id">ID</Translate> <FontAwesomeIcon icon={getSortIconByFieldName('id')} />
                </th>
                <th className="hand" onClick={sort('runId')}>
                  <Translate contentKey="booksEtlApp.ingestEvent.runId">Run Id</Translate>{' '}
                  <FontAwesomeIcon icon={getSortIconByFieldName('runId')} />
                </th>
                <th className="hand" onClick={sort('documentId')}>
                  <Translate contentKey="booksEtlApp.ingestEvent.documentId">Document Id</Translate>{' '}
                  <FontAwesomeIcon icon={getSortIconByFieldName('documentId')} />
                </th>
                <th className="hand" onClick={sort('topic')}>
                  <Translate contentKey="booksEtlApp.ingestEvent.topic">Topic</Translate>{' '}
                  <FontAwesomeIcon icon={getSortIconByFieldName('topic')} />
                </th>
                <th className="hand" onClick={sort('payload')}>
                  <Translate contentKey="booksEtlApp.ingestEvent.payload">Payload</Translate>{' '}
                  <FontAwesomeIcon icon={getSortIconByFieldName('payload')} />
                </th>
                <th className="hand" onClick={sort('createdAt')}>
                  <Translate contentKey="booksEtlApp.ingestEvent.createdAt">Created At</Translate>{' '}
                  <FontAwesomeIcon icon={getSortIconByFieldName('createdAt')} />
                </th>
                <th>
                  <Translate contentKey="booksEtlApp.ingestEvent.ingestRun">Ingest Run</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th />
              </tr>
            </thead>
            <tbody>
              {ingestEventList.map((ingestEvent, i) => (
                <tr key={`entity-${i}`} data-cy="entityTable">
                  <td>
                    <Button tag={Link} to={`/ingest-event/${ingestEvent.id}`} color="link" size="sm">
                      {ingestEvent.id}
                    </Button>
                  </td>
                  <td>{ingestEvent.runId}</td>
                  <td>{ingestEvent.documentId}</td>
                  <td>{ingestEvent.topic}</td>
                  <td>{ingestEvent.payload}</td>
                  <td>
                    {ingestEvent.createdAt ? <TextFormat type="date" value={ingestEvent.createdAt} format={APP_DATE_FORMAT} /> : null}
                  </td>
                  <td>
                    {ingestEvent.ingestRun ? <Link to={`/ingest-run/${ingestEvent.ingestRun.id}`}>{ingestEvent.ingestRun.id}</Link> : ''}
                  </td>
                  <td className="text-end">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`/ingest-event/${ingestEvent.id}`} color="info" size="sm" data-cy="entityDetailsButton">
                        <FontAwesomeIcon icon="eye" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.view">View</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`/ingest-event/${ingestEvent.id}/edit`} color="primary" size="sm" data-cy="entityEditButton">
                        <FontAwesomeIcon icon="pencil-alt" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.edit">Edit</Translate>
                        </span>
                      </Button>
                      <Button
                        onClick={() => (window.location.href = `/ingest-event/${ingestEvent.id}/delete`)}
                        color="danger"
                        size="sm"
                        data-cy="entityDeleteButton"
                      >
                        <FontAwesomeIcon icon="trash" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.delete">Delete</Translate>
                        </span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        ) : (
          !loading && (
            <div className="alert alert-warning">
              <Translate contentKey="booksEtlApp.ingestEvent.home.notFound">No Ingest Events found</Translate>
            </div>
          )
        )}
      </div>
    </div>
  );
};

export default IngestEvent;

// src/main/webapp/app/entities/ingest-event/list/ingest-event.component.ts
import { Component, NgZone, OnInit, inject, signal } from '@angular/core';
import { ActivatedRoute, Data, ParamMap, Router, RouterModule } from '@angular/router';
import { Observable, Subscription, combineLatest, filter, tap } from 'rxjs';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import SharedModule from 'app/shared/shared.module';
import { SortByDirective, SortDirective, SortService, type SortState, sortStateSignal } from 'app/shared/sort';
import { FormatMediumDatetimePipe } from 'app/shared/date';
import { FormsModule } from '@angular/forms';
import { DEFAULT_SORT_DATA, ITEM_DELETED_EVENT, SORT } from 'app/config/navigation.constants';
import { DataUtils } from 'app/core/util/data-util.service';
import { IIngestEvent } from '../ingest-event.model';
import { EntityArrayResponseType, IngestEventService } from '../service/ingest-event.service';
import { IngestEventDeleteDialogComponent } from '../delete/ingest-event-delete-dialog.component';

@Component({
  selector: 'jhi-ingest-event',
  templateUrl: './ingest-event.component.html',
  imports: [RouterModule, FormsModule, SharedModule, SortDirective, SortByDirective, FormatMediumDatetimePipe],
})
export class IngestEventComponent implements OnInit {
  subscription: Subscription | null = null;
  ingestEvents = signal<IIngestEvent[]>([]);
  isLoading = false;

  sortState = sortStateSignal({});

  public readonly router = inject(Router);
  protected readonly ingestEventService = inject(IngestEventService);
  protected readonly activatedRoute = inject(ActivatedRoute);
  protected readonly sortService = inject(SortService);
  protected dataUtils = inject(DataUtils);
  protected modalService = inject(NgbModal);
  protected ngZone = inject(NgZone);

  trackId = (item: IIngestEvent): number => this.ingestEventService.getIngestEventIdentifier(item);

  ngOnInit(): void {
    this.subscription = combineLatest([this.activatedRoute.queryParamMap, this.activatedRoute.data])
      .pipe(
        tap(([params, data]) => this.fillComponentAttributeFromRoute(params, data)),
        tap(() => {
          if (this.ingestEvents().length === 0) {
            this.load();
          } else {
            this.ingestEvents.set(this.refineData(this.ingestEvents()));
          }
        }),
      )
      .subscribe();
  }

  byteSize(base64String: string): string {
    return this.dataUtils.byteSize(base64String);
  }

  openFile(base64String: string, contentType: string | null | undefined): void {
    return this.dataUtils.openFile(base64String, contentType);
  }

  delete(ingestEvent: IIngestEvent): void {
    const modalRef = this.modalService.open(IngestEventDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.ingestEvent = ingestEvent;
    // unsubscribe not needed because closed completes on modal close
    modalRef.closed
      .pipe(
        filter(reason => reason === ITEM_DELETED_EVENT),
        tap(() => this.load()),
      )
      .subscribe();
  }

  load(): void {
    this.queryBackend().subscribe({
      next: (res: EntityArrayResponseType) => {
        this.onResponseSuccess(res);
      },
    });
  }

  navigateToWithComponentValues(event: SortState): void {
    this.handleNavigation(event);
  }

  protected fillComponentAttributeFromRoute(params: ParamMap, data: Data): void {
    this.sortState.set(this.sortService.parseSortParam(params.get(SORT) ?? data[DEFAULT_SORT_DATA]));
  }

  protected onResponseSuccess(response: EntityArrayResponseType): void {
    const dataFromBody = this.fillComponentAttributesFromResponseBody(response.body);
    this.ingestEvents.set(this.refineData(dataFromBody));
  }

  protected refineData(data: IIngestEvent[]): IIngestEvent[] {
    const { predicate, order } = this.sortState();
    return predicate && order ? data.sort(this.sortService.startSort({ predicate, order })) : data;
  }

  protected fillComponentAttributesFromResponseBody(data: IIngestEvent[] | null): IIngestEvent[] {
    return data ?? [];
  }

  protected queryBackend(): Observable<EntityArrayResponseType> {
    this.isLoading = true;
    const queryObject: any = {
      sort: this.sortService.buildSortParam(this.sortState()),
    };
    return this.ingestEventService.query(queryObject).pipe(tap(() => (this.isLoading = false)));
  }

  protected handleNavigation(sortState: SortState): void {
    const queryParamsObj = {
      sort: this.sortService.buildSortParam(sortState),
    };

    this.ngZone.run(() => {
      this.router.navigate(['./'], {
        relativeTo: this.activatedRoute,
        queryParams: queryParamsObj,
      });
    });
  }
}

<div>
  <h2 id="page-heading" data-cy="IngestEventHeading">
    <span jhiTranslate="booksEtlApp.ingestEvent.home.title">Ingest Events</span>

    <div class="d-flex justify-content-end">
      <button class="btn btn-info me-2" (click)="load()" [disabled]="isLoading">
        <fa-icon icon="sync" [animation]="isLoading ? 'spin' : undefined"></fa-icon>
        <span jhiTranslate="booksEtlApp.ingestEvent.home.refreshListLabel">Refresh list</span>
      </button>

      <button
        id="jh-create-entity"
        data-cy="entityCreateButton"
        class="btn btn-primary jh-create-entity create-ingest-event"
        [routerLink]="['/ingest-event/new']"
      >
        <fa-icon icon="plus"></fa-icon>
        <span jhiTranslate="booksEtlApp.ingestEvent.home.createLabel">Create a new Ingest Event</span>
      </button>
    </div>
  </h2>

  <jhi-alert-error />

  <jhi-alert />

  @if (ingestEvents().length === 0) {
    <div class="alert alert-warning" id="no-result">
      <span jhiTranslate="booksEtlApp.ingestEvent.home.notFound">No Ingest Events found</span>
    </div>
  } @else {
    <div class="table-responsive table-entities" id="entities">
      <table class="table table-striped" aria-describedby="page-heading">
        <thead>
          <tr jhiSort [(sortState)]="sortState" (sortChange)="navigateToWithComponentValues($event)">
            <th scope="col" jhiSortBy="id">
              <div class="d-flex">
                <span jhiTranslate="global.field.id">ID</span>

                <fa-icon class="p-1" icon="sort"></fa-icon>
              </div>
            </th>
            <th scope="col" jhiSortBy="runId">
              <div class="d-flex">
                <span jhiTranslate="booksEtlApp.ingestEvent.runId">Run Id</span>

                <fa-icon class="p-1" icon="sort"></fa-icon>
              </div>
            </th>
            <th scope="col" jhiSortBy="documentId">
              <div class="d-flex">
                <span jhiTranslate="booksEtlApp.ingestEvent.documentId">Document Id</span>

                <fa-icon class="p-1" icon="sort"></fa-icon>
              </div>
            </th>
            <th scope="col" jhiSortBy="topic">
              <div class="d-flex">
                <span jhiTranslate="booksEtlApp.ingestEvent.topic">Topic</span>

                <fa-icon class="p-1" icon="sort"></fa-icon>
              </div>
            </th>
            <th scope="col" jhiSortBy="payload">
              <div class="d-flex">
                <span jhiTranslate="booksEtlApp.ingestEvent.payload">Payload</span>

                <fa-icon class="p-1" icon="sort"></fa-icon>
              </div>
            </th>
            <th scope="col" jhiSortBy="createdAt">
              <div class="d-flex">
                <span jhiTranslate="booksEtlApp.ingestEvent.createdAt">Created At</span>

                <fa-icon class="p-1" icon="sort"></fa-icon>
              </div>
            </th>
            <th scope="col" jhiSortBy="ingestRun.id">
              <div class="d-flex">
                <span jhiTranslate="booksEtlApp.ingestEvent.ingestRun">Ingest Run</span>
                <fa-icon class="p-1" icon="sort"></fa-icon>
              </div>
            </th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
          @for (ingestEvent of ingestEvents(); track trackId(ingestEvent)) {
            <tr data-cy="entityTable">
              <td>
                <a [routerLink]="['/ingest-event', ingestEvent.id, 'view']">{{ ingestEvent.id }}</a>
              </td>
              <td>{{ ingestEvent.runId }}</td>
              <td>{{ ingestEvent.documentId }}</td>
              <td>{{ ingestEvent.topic }}</td>
              <td>{{ ingestEvent.payload }}</td>
              <td>{{ ingestEvent.createdAt | formatMediumDatetime }}</td>
              <td>
                @if (ingestEvent.ingestRun) {
                  <div>
                    <a [routerLink]="['/ingest-run', ingestEvent.ingestRun.id, 'view']">{{ ingestEvent.ingestRun.id }}</a>
                  </div>
                }
              </td>
              <td class="text-end">
                <div class="btn-group">
                  <a [routerLink]="['/ingest-event', ingestEvent.id, 'view']" class="btn btn-info btn-sm" data-cy="entityDetailsButton">
                    <fa-icon icon="eye"></fa-icon>
                    <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
                  </a>

                  <a [routerLink]="['/ingest-event', ingestEvent.id, 'edit']" class="btn btn-primary btn-sm" data-cy="entityEditButton">
                    <fa-icon icon="pencil-alt"></fa-icon>
                    <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
                  </a>

                  <button type="submit" (click)="delete(ingestEvent)" class="btn btn-danger btn-sm" data-cy="entityDeleteButton">
                    <fa-icon icon="times"></fa-icon>
                    <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
                  </button>
                </div>
              </td>
            </tr>
          }
        </tbody>
      </table>
    </div>
  }
</div>
