// src/main/webapp/app/entities/book-file/list/book-file.component.ts
import { Component, NgZone, OnInit, inject, signal } from '@angular/core';
import { HttpHeaders } from '@angular/common/http';
import { ActivatedRoute, Data, ParamMap, Router, RouterModule } from '@angular/router';
import { Observable, Subscription, combineLatest, filter, tap } from 'rxjs';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import SharedModule from 'app/shared/shared.module';
import { SortByDirective, SortDirective, SortService, type SortState, sortStateSignal } from 'app/shared/sort';
import { FormatMediumDatetimePipe } from 'app/shared/date';
import { ItemCountComponent } from 'app/shared/pagination';
import { FormsModule } from '@angular/forms';
import { ITEMS_PER_PAGE, PAGE_HEADER, TOTAL_COUNT_RESPONSE_HEADER } from 'app/config/pagination.constants';
import { DEFAULT_SORT_DATA, ITEM_DELETED_EVENT, SORT } from 'app/config/navigation.constants';
import { DataUtils } from 'app/core/util/data-util.service';
import { IBookFile } from '../book-file.model';

import { BookFileService, EntityArrayResponseType } from '../service/book-file.service';
import { BookFileDeleteDialogComponent } from '../delete/book-file-delete-dialog.component';

@Component({
  selector: 'jhi-book-file',
  templateUrl: './book-file.component.html',
  imports: [RouterModule, FormsModule, SharedModule, SortDirective, SortByDirective, FormatMediumDatetimePipe, ItemCountComponent],
})
export class BookFileComponent implements OnInit {
  subscription: Subscription | null = null;
  bookFiles = signal<IBookFile[]>([]);
  isLoading = false;

  sortState = sortStateSignal({});

  itemsPerPage = ITEMS_PER_PAGE;
  totalItems = 0;
  page = 1;

  public readonly router = inject(Router);
  protected readonly bookFileService = inject(BookFileService);
  protected readonly activatedRoute = inject(ActivatedRoute);
  protected readonly sortService = inject(SortService);
  protected dataUtils = inject(DataUtils);
  protected modalService = inject(NgbModal);
  protected ngZone = inject(NgZone);

  trackId = (item: IBookFile): number => this.bookFileService.getBookFileIdentifier(item);

  ngOnInit(): void {
    this.subscription = combineLatest([this.activatedRoute.queryParamMap, this.activatedRoute.data])
      .pipe(
        tap(([params, data]) => this.fillComponentAttributeFromRoute(params, data)),
        tap(() => this.load()),
      )
      .subscribe();
  }

  byteSize(base64String: string): string {
    return this.dataUtils.byteSize(base64String);
  }

  openFile(base64String: string, contentType: string | null | undefined): void {
    return this.dataUtils.openFile(base64String, contentType);
  }

  delete(bookFile: IBookFile): void {
    const modalRef = this.modalService.open(BookFileDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.bookFile = bookFile;
    // unsubscribe not needed because closed completes on modal close
    modalRef.closed
      .pipe(
        filter(reason => reason === ITEM_DELETED_EVENT),
        tap(() => this.load()),
      )
      .subscribe();
  }

  load(): void {
    this.queryBackend().subscribe({
      next: (res: EntityArrayResponseType) => {
        this.onResponseSuccess(res);
      },
    });
  }

  navigateToWithComponentValues(event: SortState): void {
    this.handleNavigation(this.page, event);
  }

  navigateToPage(page: number): void {
    this.handleNavigation(page, this.sortState());
  }

  protected fillComponentAttributeFromRoute(params: ParamMap, data: Data): void {
    const page = params.get(PAGE_HEADER);
    this.page = +(page ?? 1);
    this.sortState.set(this.sortService.parseSortParam(params.get(SORT) ?? data[DEFAULT_SORT_DATA]));
  }

  protected onResponseSuccess(response: EntityArrayResponseType): void {
    this.fillComponentAttributesFromResponseHeader(response.headers);
    const dataFromBody = this.fillComponentAttributesFromResponseBody(response.body);
    this.bookFiles.set(dataFromBody);
  }

  protected fillComponentAttributesFromResponseBody(data: IBookFile[] | null): IBookFile[] {
    return data ?? [];
  }

  protected fillComponentAttributesFromResponseHeader(headers: HttpHeaders): void {
    this.totalItems = Number(headers.get(TOTAL_COUNT_RESPONSE_HEADER));
  }

  protected queryBackend(): Observable<EntityArrayResponseType> {
    const { page } = this;

    this.isLoading = true;
    const pageToLoad: number = page;
    const queryObject: any = {
      page: pageToLoad - 1,
      size: this.itemsPerPage,
      eagerload: true,
      sort: this.sortService.buildSortParam(this.sortState()),
    };
    return this.bookFileService.query(queryObject).pipe(tap(() => (this.isLoading = false)));
  }

  protected handleNavigation(page: number, sortState: SortState): void {
    const queryParamsObj = {
      page,
      size: this.itemsPerPage,
      sort: this.sortService.buildSortParam(sortState),
    };

    this.ngZone.run(() => {
      this.router.navigate(['./'], {
        relativeTo: this.activatedRoute,
        queryParams: queryParamsObj,
      });
    });
  }
}

<div>
  <h2 id="page-heading" data-cy="BookFileHeading">
    <span jhiTranslate="booksEtlApp.bookFile.home.title">Book Files</span>

    <div class="d-flex justify-content-end">
      <button class="btn btn-info me-2" (click)="load()" [disabled]="isLoading">
        <fa-icon icon="sync" [animation]="isLoading ? 'spin' : undefined"></fa-icon>
        <span jhiTranslate="booksEtlApp.bookFile.home.refreshListLabel">Refresh list</span>
      </button>

      <button
        id="jh-create-entity"
        data-cy="entityCreateButton"
        class="btn btn-primary jh-create-entity create-book-file"
        [routerLink]="['/book-file/new']"
      >
        <fa-icon icon="plus"></fa-icon>
        <span jhiTranslate="booksEtlApp.bookFile.home.createLabel">Create a new Book File</span>
      </button>
    </div>
  </h2>

  <jhi-alert-error />

  <jhi-alert />

  @if (bookFiles().length === 0) {
    <div class="alert alert-warning" id="no-result">
      <span jhiTranslate="booksEtlApp.bookFile.home.notFound">No Book Files found</span>
    </div>
  } @else {
    <div class="table-responsive table-entities" id="entities">
      <table class="table table-striped" aria-describedby="page-heading">
        <thead>
          <tr jhiSort [(sortState)]="sortState" (sortChange)="navigateToWithComponentValues($event)">
            <th scope="col" jhiSortBy="id">
              <div class="d-flex">
                <span jhiTranslate="global.field.id">ID</span>

                <fa-icon class="p-1" icon="sort"></fa-icon>
              </div>
            </th>
            <th scope="col" jhiSortBy="pathNorm">
              <div class="d-flex">
                <span jhiTranslate="booksEtlApp.bookFile.pathNorm">Path Norm</span>

                <fa-icon class="p-1" icon="sort"></fa-icon>
              </div>
            </th>
            <th scope="col" jhiSortBy="sha256">
              <div class="d-flex">
                <span jhiTranslate="booksEtlApp.bookFile.sha256">Sha 256</span>

                <fa-icon class="p-1" icon="sort"></fa-icon>
              </div>
            </th>
            <th scope="col" jhiSortBy="sizeBytes">
              <div class="d-flex">
                <span jhiTranslate="booksEtlApp.bookFile.sizeBytes">Size Bytes</span>

                <fa-icon class="p-1" icon="sort"></fa-icon>
              </div>
            </th>
            <th scope="col" jhiSortBy="mtime">
              <div class="d-flex">
                <span jhiTranslate="booksEtlApp.bookFile.mtime">Mtime</span>

                <fa-icon class="p-1" icon="sort"></fa-icon>
              </div>
            </th>
            <th scope="col" jhiSortBy="storageUri">
              <div class="d-flex">
                <span jhiTranslate="booksEtlApp.bookFile.storageUri">Storage Uri</span>

                <fa-icon class="p-1" icon="sort"></fa-icon>
              </div>
            </th>
            <th scope="col" jhiSortBy="firstSeenAt">
              <div class="d-flex">
                <span jhiTranslate="booksEtlApp.bookFile.firstSeenAt">First Seen At</span>

                <fa-icon class="p-1" icon="sort"></fa-icon>
              </div>
            </th>
            <th scope="col" jhiSortBy="lastSeenAt">
              <div class="d-flex">
                <span jhiTranslate="booksEtlApp.bookFile.lastSeenAt">Last Seen At</span>

                <fa-icon class="p-1" icon="sort"></fa-icon>
              </div>
            </th>
            <th scope="col" jhiSortBy="book.documentId">
              <div class="d-flex">
                <span jhiTranslate="booksEtlApp.bookFile.book">Book</span>
                <fa-icon class="p-1" icon="sort"></fa-icon>
              </div>
            </th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
          @for (bookFile of bookFiles(); track trackId(bookFile)) {
            <tr data-cy="entityTable">
              <td>
                <a [routerLink]="['/book-file', bookFile.id, 'view']">{{ bookFile.id }}</a>
              </td>
              <td>{{ bookFile.pathNorm }}</td>
              <td>{{ bookFile.sha256 }}</td>
              <td>{{ bookFile.sizeBytes }}</td>
              <td>{{ bookFile.mtime | formatMediumDatetime }}</td>
              <td>{{ bookFile.storageUri }}</td>
              <td>{{ bookFile.firstSeenAt | formatMediumDatetime }}</td>
              <td>{{ bookFile.lastSeenAt | formatMediumDatetime }}</td>
              <td>
                @if (bookFile.book) {
                  <div>
                    <a [routerLink]="['/book', bookFile.book.id, 'view']">{{ bookFile.book.documentId }}</a>
                  </div>
                }
              </td>
              <td class="text-end">
                <div class="btn-group">
                  <a [routerLink]="['/book-file', bookFile.id, 'view']" class="btn btn-info btn-sm" data-cy="entityDetailsButton">
                    <fa-icon icon="eye"></fa-icon>
                    <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
                  </a>

                  <a [routerLink]="['/book-file', bookFile.id, 'edit']" class="btn btn-primary btn-sm" data-cy="entityEditButton">
                    <fa-icon icon="pencil-alt"></fa-icon>
                    <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
                  </a>

                  <button type="submit" (click)="delete(bookFile)" class="btn btn-danger btn-sm" data-cy="entityDeleteButton">
                    <fa-icon icon="times"></fa-icon>
                    <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
                  </button>
                </div>
              </td>
            </tr>
          }
        </tbody>
      </table>
    </div>
  }
  @if (bookFiles().length > 0) {
    <div>
      <div class="d-flex justify-content-center">
        <jhi-item-count [params]="{ page, totalItems, itemsPerPage }" />
      </div>

      <div class="d-flex justify-content-center">
        <ngb-pagination
          [collectionSize]="totalItems"
          [page]="page"
          [pageSize]="itemsPerPage"
          [maxSize]="5"
          [rotate]="true"
          [boundaryLinks]="true"
          (pageChange)="navigateToPage($event)"
        ></ngb-pagination>
      </div>
    </div>
  }
</div>

// src/main/webapp/app/entities/book-file/book-file.tsx
import React, { useEffect, useState } from 'react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { Button, Table } from 'reactstrap';
import { JhiItemCount, JhiPagination, TextFormat, Translate, getPaginationState } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faSort, faSortDown, faSortUp } from '@fortawesome/free-solid-svg-icons';
import { APP_DATE_FORMAT } from 'app/config/constants';
import { ASC, DESC, ITEMS_PER_PAGE, SORT } from 'app/shared/util/pagination.constants';
import { overridePaginationStateWithQueryParams } from 'app/shared/util/entity-utils';
import { useAppDispatch, useAppSelector } from 'app/config/store';

import { getEntities } from './book-file.reducer';

export const BookFile = () => {
  const dispatch = useAppDispatch();

  const pageLocation = useLocation();
  const navigate = useNavigate();

  const [paginationState, setPaginationState] = useState(
    overridePaginationStateWithQueryParams(getPaginationState(pageLocation, ITEMS_PER_PAGE, 'id'), pageLocation.search),
  );

  const bookFileList = useAppSelector(state => state.bookFile.entities);
  const loading = useAppSelector(state => state.bookFile.loading);
  const totalItems = useAppSelector(state => state.bookFile.totalItems);

  const getAllEntities = () => {
    dispatch(
      getEntities({
        page: paginationState.activePage - 1,
        size: paginationState.itemsPerPage,
        sort: `${paginationState.sort},${paginationState.order}`,
      }),
    );
  };

  const sortEntities = () => {
    getAllEntities();
    const endURL = `?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`;
    if (pageLocation.search !== endURL) {
      navigate(`${pageLocation.pathname}${endURL}`);
    }
  };

  useEffect(() => {
    sortEntities();
  }, [paginationState.activePage, paginationState.order, paginationState.sort]);

  useEffect(() => {
    const params = new URLSearchParams(pageLocation.search);
    const page = params.get('page');
    const sort = params.get(SORT);
    if (page && sort) {
      const sortSplit = sort.split(',');
      setPaginationState({
        ...paginationState,
        activePage: +page,
        sort: sortSplit[0],
        order: sortSplit[1],
      });
    }
  }, [pageLocation.search]);

  const sort = p => () => {
    setPaginationState({
      ...paginationState,
      order: paginationState.order === ASC ? DESC : ASC,
      sort: p,
    });
  };

  const handlePagination = currentPage =>
    setPaginationState({
      ...paginationState,
      activePage: currentPage,
    });

  const handleSyncList = () => {
    sortEntities();
  };

  const getSortIconByFieldName = (fieldName: string) => {
    const sortFieldName = paginationState.sort;
    const order = paginationState.order;
    if (sortFieldName !== fieldName) {
      return faSort;
    }
    return order === ASC ? faSortUp : faSortDown;
  };

  return (
    <div>
      <h2 id="book-file-heading" data-cy="BookFileHeading">
        <Translate contentKey="booksEtlApp.bookFile.home.title">Book Files</Translate>
        <div className="d-flex justify-content-end">
          <Button className="me-2" color="info" onClick={handleSyncList} disabled={loading}>
            <FontAwesomeIcon icon="sync" spin={loading} />{' '}
            <Translate contentKey="booksEtlApp.bookFile.home.refreshListLabel">Refresh List</Translate>
          </Button>
          <Link to="/book-file/new" className="btn btn-primary jh-create-entity" id="jh-create-entity" data-cy="entityCreateButton">
            <FontAwesomeIcon icon="plus" />
            &nbsp;
            <Translate contentKey="booksEtlApp.bookFile.home.createLabel">Create new Book File</Translate>
          </Link>
        </div>
      </h2>
      <div className="table-responsive">
        {bookFileList && bookFileList.length > 0 ? (
          <Table responsive>
            <thead>
              <tr>
                <th className="hand" onClick={sort('id')}>
                  <Translate contentKey="booksEtlApp.bookFile.id">ID</Translate> <FontAwesomeIcon icon={getSortIconByFieldName('id')} />
                </th>
                <th className="hand" onClick={sort('pathNorm')}>
                  <Translate contentKey="booksEtlApp.bookFile.pathNorm">Path Norm</Translate>{' '}
                  <FontAwesomeIcon icon={getSortIconByFieldName('pathNorm')} />
                </th>
                <th className="hand" onClick={sort('sha256')}>
                  <Translate contentKey="booksEtlApp.bookFile.sha256">Sha 256</Translate>{' '}
                  <FontAwesomeIcon icon={getSortIconByFieldName('sha256')} />
                </th>
                <th className="hand" onClick={sort('sizeBytes')}>
                  <Translate contentKey="booksEtlApp.bookFile.sizeBytes">Size Bytes</Translate>{' '}
                  <FontAwesomeIcon icon={getSortIconByFieldName('sizeBytes')} />
                </th>
                <th className="hand" onClick={sort('mtime')}>
                  <Translate contentKey="booksEtlApp.bookFile.mtime">Mtime</Translate>{' '}
                  <FontAwesomeIcon icon={getSortIconByFieldName('mtime')} />
                </th>
                <th className="hand" onClick={sort('storageUri')}>
                  <Translate contentKey="booksEtlApp.bookFile.storageUri">Storage Uri</Translate>{' '}
                  <FontAwesomeIcon icon={getSortIconByFieldName('storageUri')} />
                </th>
                <th className="hand" onClick={sort('firstSeenAt')}>
                  <Translate contentKey="booksEtlApp.bookFile.firstSeenAt">First Seen At</Translate>{' '}
                  <FontAwesomeIcon icon={getSortIconByFieldName('firstSeenAt')} />
                </th>
                <th className="hand" onClick={sort('lastSeenAt')}>
                  <Translate contentKey="booksEtlApp.bookFile.lastSeenAt">Last Seen At</Translate>{' '}
                  <FontAwesomeIcon icon={getSortIconByFieldName('lastSeenAt')} />
                </th>
                <th>
                  <Translate contentKey="booksEtlApp.bookFile.book">Book</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th />
              </tr>
            </thead>
            <tbody>
              {bookFileList.map((bookFile, i) => (
                <tr key={`entity-${i}`} data-cy="entityTable">
                  <td>
                    <Button tag={Link} to={`/book-file/${bookFile.id}`} color="link" size="sm">
                      {bookFile.id}
                    </Button>
                  </td>
                  <td>{bookFile.pathNorm}</td>
                  <td>{bookFile.sha256}</td>
                  <td>{bookFile.sizeBytes}</td>
                  <td>{bookFile.mtime ? <TextFormat type="date" value={bookFile.mtime} format={APP_DATE_FORMAT} /> : null}</td>
                  <td>{bookFile.storageUri}</td>
                  <td>{bookFile.firstSeenAt ? <TextFormat type="date" value={bookFile.firstSeenAt} format={APP_DATE_FORMAT} /> : null}</td>
                  <td>{bookFile.lastSeenAt ? <TextFormat type="date" value={bookFile.lastSeenAt} format={APP_DATE_FORMAT} /> : null}</td>
                  <td>{bookFile.book ? <Link to={`/book/${bookFile.book.id}`}>{bookFile.book.documentId}</Link> : ''}</td>
                  <td className="text-end">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`/book-file/${bookFile.id}`} color="info" size="sm" data-cy="entityDetailsButton">
                        <FontAwesomeIcon icon="eye" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.view">View</Translate>
                        </span>
                      </Button>
                      <Button
                        tag={Link}
                        to={`/book-file/${bookFile.id}/edit?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`}
                        color="primary"
                        size="sm"
                        data-cy="entityEditButton"
                      >
                        <FontAwesomeIcon icon="pencil-alt" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.edit">Edit</Translate>
                        </span>
                      </Button>
                      <Button
                        onClick={() =>
                          (window.location.href = `/book-file/${bookFile.id}/delete?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`)
                        }
                        color="danger"
                        size="sm"
                        data-cy="entityDeleteButton"
                      >
                        <FontAwesomeIcon icon="trash" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.delete">Delete</Translate>
                        </span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        ) : (
          !loading && (
            <div className="alert alert-warning">
              <Translate contentKey="booksEtlApp.bookFile.home.notFound">No Book Files found</Translate>
            </div>
          )
        )}
      </div>
      {totalItems ? (
        <div className={bookFileList && bookFileList.length > 0 ? '' : 'd-none'}>
          <div className="justify-content-center d-flex">
            <JhiItemCount page={paginationState.activePage} total={totalItems} itemsPerPage={paginationState.itemsPerPage} i18nEnabled />
          </div>
          <div className="justify-content-center d-flex">
            <JhiPagination
              activePage={paginationState.activePage}
              onSelect={handlePagination}
              maxButtons={5}
              itemsPerPage={paginationState.itemsPerPage}
              totalItems={totalItems}
            />
          </div>
        </div>
      ) : (
        ''
      )}
    </div>
  );
};

export default BookFile;
