// src/main/webapp/app/entities/book-file/detail/book-file-detail.component.ts
import { Component, inject, input } from '@angular/core';
import { RouterModule } from '@angular/router';

import SharedModule from 'app/shared/shared.module';
import { FormatMediumDatetimePipe } from 'app/shared/date';
import { DataUtils } from 'app/core/util/data-util.service';
import { IBookFile } from '../book-file.model';

@Component({
  selector: 'jhi-book-file-detail',
  templateUrl: './book-file-detail.component.html',
  imports: [SharedModule, RouterModule, FormatMediumDatetimePipe],
})
export class BookFileDetailComponent {
  bookFile = input<IBookFile | null>(null);

  protected dataUtils = inject(DataUtils);

  byteSize(base64String: string): string {
    return this.dataUtils.byteSize(base64String);
  }

  openFile(base64String: string, contentType: string | null | undefined): void {
    this.dataUtils.openFile(base64String, contentType);
  }

  previousState(): void {
    window.history.back();
  }
}

<div class="d-flex justify-content-center">
  <div class="col-8">
    @if (bookFile(); as bookFileRef) {
      <div>
        <h2 data-cy="bookFileDetailsHeading"><span jhiTranslate="booksEtlApp.bookFile.detail.title">Book File</span></h2>

        <hr />

        <jhi-alert-error />

        <jhi-alert />

        <dl class="row-md jh-entity-details">
          <dt><span jhiTranslate="global.field.id">ID</span></dt>
          <dd>
            <span>{{ bookFileRef.id }}</span>
          </dd>
          <dt><span jhiTranslate="booksEtlApp.bookFile.pathNorm">Path Norm</span></dt>
          <dd>
            <span>{{ bookFileRef.pathNorm }}</span>
          </dd>
          <dt><span jhiTranslate="booksEtlApp.bookFile.sha256">Sha 256</span></dt>
          <dd>
            <span>{{ bookFileRef.sha256 }}</span>
          </dd>
          <dt><span jhiTranslate="booksEtlApp.bookFile.sizeBytes">Size Bytes</span></dt>
          <dd>
            <span>{{ bookFileRef.sizeBytes }}</span>
          </dd>
          <dt><span jhiTranslate="booksEtlApp.bookFile.mtime">Mtime</span></dt>
          <dd>
            <span>{{ bookFileRef.mtime | formatMediumDatetime }}</span>
          </dd>
          <dt><span jhiTranslate="booksEtlApp.bookFile.storageUri">Storage Uri</span></dt>
          <dd>
            <span>{{ bookFileRef.storageUri }}</span>
          </dd>
          <dt><span jhiTranslate="booksEtlApp.bookFile.firstSeenAt">First Seen At</span></dt>
          <dd>
            <span>{{ bookFileRef.firstSeenAt | formatMediumDatetime }}</span>
          </dd>
          <dt><span jhiTranslate="booksEtlApp.bookFile.lastSeenAt">Last Seen At</span></dt>
          <dd>
            <span>{{ bookFileRef.lastSeenAt | formatMediumDatetime }}</span>
          </dd>
          <dt><span jhiTranslate="booksEtlApp.bookFile.book">Book</span></dt>
          <dd>
            @if (bookFile()!.book) {
              <div>
                <a [routerLink]="['/book', bookFile()!.book?.id, 'view']">{{ bookFileRef.book?.documentId }}</a>
              </div>
            }
          </dd>
        </dl>

        <button type="submit" (click)="previousState()" class="btn btn-info" data-cy="entityDetailsBackButton">
          <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back">Back</span>
        </button>

        <button type="button" [routerLink]="['/book-file', bookFileRef.id, 'edit']" class="btn btn-primary">
          <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span jhiTranslate="entity.action.edit">Edit</span>
        </button>
      </div>
    }
  </div>
</div>

// src/main/webapp/app/entities/book-file/book-file-detail.tsx
import React, { useEffect } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Button, Col, Row } from 'reactstrap';
import { TextFormat, Translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { APP_DATE_FORMAT } from 'app/config/constants';
import { useAppDispatch, useAppSelector } from 'app/config/store';

import { getEntity } from './book-file.reducer';

export const BookFileDetail = () => {
  const dispatch = useAppDispatch();

  const { id } = useParams<'id'>();

  useEffect(() => {
    dispatch(getEntity(id));
  }, []);

  const bookFileEntity = useAppSelector(state => state.bookFile.entity);
  return (
    <Row>
      <Col md="8">
        <h2 data-cy="bookFileDetailsHeading">
          <Translate contentKey="booksEtlApp.bookFile.detail.title">BookFile</Translate>
        </h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="id">
              <Translate contentKey="global.field.id">ID</Translate>
            </span>
          </dt>
          <dd>{bookFileEntity.id}</dd>
          <dt>
            <span id="pathNorm">
              <Translate contentKey="booksEtlApp.bookFile.pathNorm">Path Norm</Translate>
            </span>
          </dt>
          <dd>{bookFileEntity.pathNorm}</dd>
          <dt>
            <span id="sha256">
              <Translate contentKey="booksEtlApp.bookFile.sha256">Sha 256</Translate>
            </span>
          </dt>
          <dd>{bookFileEntity.sha256}</dd>
          <dt>
            <span id="sizeBytes">
              <Translate contentKey="booksEtlApp.bookFile.sizeBytes">Size Bytes</Translate>
            </span>
          </dt>
          <dd>{bookFileEntity.sizeBytes}</dd>
          <dt>
            <span id="mtime">
              <Translate contentKey="booksEtlApp.bookFile.mtime">Mtime</Translate>
            </span>
          </dt>
          <dd>{bookFileEntity.mtime ? <TextFormat value={bookFileEntity.mtime} type="date" format={APP_DATE_FORMAT} /> : null}</dd>
          <dt>
            <span id="storageUri">
              <Translate contentKey="booksEtlApp.bookFile.storageUri">Storage Uri</Translate>
            </span>
          </dt>
          <dd>{bookFileEntity.storageUri}</dd>
          <dt>
            <span id="firstSeenAt">
              <Translate contentKey="booksEtlApp.bookFile.firstSeenAt">First Seen At</Translate>
            </span>
          </dt>
          <dd>
            {bookFileEntity.firstSeenAt ? <TextFormat value={bookFileEntity.firstSeenAt} type="date" format={APP_DATE_FORMAT} /> : null}
          </dd>
          <dt>
            <span id="lastSeenAt">
              <Translate contentKey="booksEtlApp.bookFile.lastSeenAt">Last Seen At</Translate>
            </span>
          </dt>
          <dd>
            {bookFileEntity.lastSeenAt ? <TextFormat value={bookFileEntity.lastSeenAt} type="date" format={APP_DATE_FORMAT} /> : null}
          </dd>
          <dt>
            <Translate contentKey="booksEtlApp.bookFile.book">Book</Translate>
          </dt>
          <dd>{bookFileEntity.book ? bookFileEntity.book.documentId : ''}</dd>
        </dl>
        <Button tag={Link} to="/book-file" replace color="info" data-cy="entityDetailsBackButton">
          <FontAwesomeIcon icon="arrow-left" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.back">Back</Translate>
          </span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/book-file/${bookFileEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.edit">Edit</Translate>
          </span>
        </Button>
      </Col>
    </Row>
  );
};

export default BookFileDetail;
