// src/main/webapp/app/entities/ingest-event/ingest-event-delete-dialog.tsx
import React, { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { Button, Modal, ModalBody, ModalFooter, ModalHeader } from 'reactstrap';
import { Translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { useAppDispatch, useAppSelector } from 'app/config/store';
import { deleteEntity, getEntity } from './ingest-event.reducer';

export const IngestEventDeleteDialog = () => {
  const dispatch = useAppDispatch();
  const navigate = useNavigate();
  const { id } = useParams<'id'>();

  const [loadModal, setLoadModal] = useState(false);

  useEffect(() => {
    dispatch(getEntity(id));
    setLoadModal(true);
  }, []);

  const ingestEventEntity = useAppSelector(state => state.ingestEvent.entity);
  const updateSuccess = useAppSelector(state => state.ingestEvent.updateSuccess);

  const handleClose = () => {
    navigate('/ingest-event');
  };

  useEffect(() => {
    if (updateSuccess && loadModal) {
      handleClose();
      setLoadModal(false);
    }
  }, [updateSuccess]);

  const confirmDelete = () => {
    dispatch(deleteEntity(ingestEventEntity.id));
  };

  return (
    <Modal isOpen toggle={handleClose}>
      <ModalHeader toggle={handleClose} data-cy="ingestEventDeleteDialogHeading">
        <Translate contentKey="entity.delete.title">Confirm delete operation</Translate>
      </ModalHeader>
      <ModalBody id="booksEtlApp.ingestEvent.delete.question">
        <Translate contentKey="booksEtlApp.ingestEvent.delete.question" interpolate={{ id: ingestEventEntity.id }}>
          Are you sure you want to delete this IngestEvent?
        </Translate>
      </ModalBody>
      <ModalFooter>
        <Button color="secondary" onClick={handleClose}>
          <FontAwesomeIcon icon="ban" />
          &nbsp;
          <Translate contentKey="entity.action.cancel">Cancel</Translate>
        </Button>
        <Button id="jhi-confirm-delete-ingestEvent" data-cy="entityConfirmDeleteButton" color="danger" onClick={confirmDelete}>
          <FontAwesomeIcon icon="trash" />
          &nbsp;
          <Translate contentKey="entity.action.delete">Delete</Translate>
        </Button>
      </ModalFooter>
    </Modal>
  );
};

export default IngestEventDeleteDialog;

// src/main/webapp/app/entities/ingest-event/delete/ingest-event-delete-dialog.component.ts
import { Component, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { NgbActiveModal } from '@ng-bootstrap/ng-bootstrap';

import SharedModule from 'app/shared/shared.module';
import { ITEM_DELETED_EVENT } from 'app/config/navigation.constants';
import { IIngestEvent } from '../ingest-event.model';
import { IngestEventService } from '../service/ingest-event.service';

@Component({
  templateUrl: './ingest-event-delete-dialog.component.html',
  imports: [SharedModule, FormsModule],
})
export class IngestEventDeleteDialogComponent {
  ingestEvent?: IIngestEvent;

  protected ingestEventService = inject(IngestEventService);
  protected activeModal = inject(NgbActiveModal);

  cancel(): void {
    this.activeModal.dismiss();
  }

  confirmDelete(id: number): void {
    this.ingestEventService.delete(id).subscribe(() => {
      this.activeModal.close(ITEM_DELETED_EVENT);
    });
  }
}

@if (ingestEvent) {
  <form name="deleteForm" (ngSubmit)="confirmDelete(ingestEvent.id!)">
    <div class="modal-header">
      <h4 class="modal-title" data-cy="ingestEventDeleteDialogHeading" jhiTranslate="entity.delete.title">Confirm delete operation</h4>
    </div>

    <div class="modal-body">
      <jhi-alert-error />
      <p
        id="jhi-delete-ingestEvent-heading"
        jhiTranslate="booksEtlApp.ingestEvent.delete.question"
        [translateValues]="{ id: ingestEvent.id }"
      >
        Are you sure you want to delete Ingest Event {{ ingestEvent.id }}?
      </p>
    </div>

    <div class="modal-footer">
      <button type="button" class="btn btn-secondary" data-dismiss="modal" (click)="cancel()">
        <fa-icon icon="ban"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
      </button>

      <button id="jhi-confirm-delete-ingestEvent" data-cy="entityConfirmDeleteButton" type="submit" class="btn btn-danger">
        <fa-icon icon="times"></fa-icon>&nbsp;<span jhiTranslate="entity.action.delete">Delete</span>
      </button>
    </div>
  </form>
}
