// src/main/webapp/app/entities/ingest-run/ingest-run-delete-dialog.tsx
import React, { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { Button, Modal, ModalBody, ModalFooter, ModalHeader } from 'reactstrap';
import { Translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { useAppDispatch, useAppSelector } from 'app/config/store';
import { deleteEntity, getEntity } from './ingest-run.reducer';

export const IngestRunDeleteDialog = () => {
  const dispatch = useAppDispatch();
  const navigate = useNavigate();
  const { id } = useParams<'id'>();

  const [loadModal, setLoadModal] = useState(false);

  useEffect(() => {
    dispatch(getEntity(id));
    setLoadModal(true);
  }, []);

  const ingestRunEntity = useAppSelector(state => state.ingestRun.entity);
  const updateSuccess = useAppSelector(state => state.ingestRun.updateSuccess);

  const handleClose = () => {
    navigate('/ingest-run');
  };

  useEffect(() => {
    if (updateSuccess && loadModal) {
      handleClose();
      setLoadModal(false);
    }
  }, [updateSuccess]);

  const confirmDelete = () => {
    dispatch(deleteEntity(ingestRunEntity.id));
  };

  return (
    <Modal isOpen toggle={handleClose}>
      <ModalHeader toggle={handleClose} data-cy="ingestRunDeleteDialogHeading">
        <Translate contentKey="entity.delete.title">Confirm delete operation</Translate>
      </ModalHeader>
      <ModalBody id="booksEtlApp.ingestRun.delete.question">
        <Translate contentKey="booksEtlApp.ingestRun.delete.question" interpolate={{ id: ingestRunEntity.id }}>
          Are you sure you want to delete this IngestRun?
        </Translate>
      </ModalBody>
      <ModalFooter>
        <Button color="secondary" onClick={handleClose}>
          <FontAwesomeIcon icon="ban" />
          &nbsp;
          <Translate contentKey="entity.action.cancel">Cancel</Translate>
        </Button>
        <Button id="jhi-confirm-delete-ingestRun" data-cy="entityConfirmDeleteButton" color="danger" onClick={confirmDelete}>
          <FontAwesomeIcon icon="trash" />
          &nbsp;
          <Translate contentKey="entity.action.delete">Delete</Translate>
        </Button>
      </ModalFooter>
    </Modal>
  );
};

export default IngestRunDeleteDialog;

// src/main/webapp/app/entities/ingest-run/delete/ingest-run-delete-dialog.component.ts
import { Component, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { NgbActiveModal } from '@ng-bootstrap/ng-bootstrap';

import SharedModule from 'app/shared/shared.module';
import { ITEM_DELETED_EVENT } from 'app/config/navigation.constants';
import { IIngestRun } from '../ingest-run.model';
import { IngestRunService } from '../service/ingest-run.service';

@Component({
  templateUrl: './ingest-run-delete-dialog.component.html',
  imports: [SharedModule, FormsModule],
})
export class IngestRunDeleteDialogComponent {
  ingestRun?: IIngestRun;

  protected ingestRunService = inject(IngestRunService);
  protected activeModal = inject(NgbActiveModal);

  cancel(): void {
    this.activeModal.dismiss();
  }

  confirmDelete(id: number): void {
    this.ingestRunService.delete(id).subscribe(() => {
      this.activeModal.close(ITEM_DELETED_EVENT);
    });
  }
}

@if (ingestRun) {
  <form name="deleteForm" (ngSubmit)="confirmDelete(ingestRun.id!)">
    <div class="modal-header">
      <h4 class="modal-title" data-cy="ingestRunDeleteDialogHeading" jhiTranslate="entity.delete.title">Confirm delete operation</h4>
    </div>

    <div class="modal-body">
      <jhi-alert-error />
      <p id="jhi-delete-ingestRun-heading" jhiTranslate="booksEtlApp.ingestRun.delete.question" [translateValues]="{ id: ingestRun.id }">
        Are you sure you want to delete Ingest Run {{ ingestRun.id }}?
      </p>
    </div>

    <div class="modal-footer">
      <button type="button" class="btn btn-secondary" data-dismiss="modal" (click)="cancel()">
        <fa-icon icon="ban"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
      </button>

      <button id="jhi-confirm-delete-ingestRun" data-cy="entityConfirmDeleteButton" type="submit" class="btn btn-danger">
        <fa-icon icon="times"></fa-icon>&nbsp;<span jhiTranslate="entity.action.delete">Delete</span>
      </button>
    </div>
  </form>
}
