// src/main/webapp/app/entities/ingest-run/list/ingest-run.component.ts
import { Component, NgZone, OnInit, inject, signal } from '@angular/core';
import { ActivatedRoute, Data, ParamMap, Router, RouterModule } from '@angular/router';
import { Observable, Subscription, combineLatest, filter, tap } from 'rxjs';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import SharedModule from 'app/shared/shared.module';
import { SortByDirective, SortDirective, SortService, type SortState, sortStateSignal } from 'app/shared/sort';
import { FormatMediumDatetimePipe } from 'app/shared/date';
import { FormsModule } from '@angular/forms';
import { DEFAULT_SORT_DATA, ITEM_DELETED_EVENT, SORT } from 'app/config/navigation.constants';
import { IIngestRun } from '../ingest-run.model';
import { EntityArrayResponseType, IngestRunService } from '../service/ingest-run.service';
import { IngestRunDeleteDialogComponent } from '../delete/ingest-run-delete-dialog.component';

@Component({
  selector: 'jhi-ingest-run',
  templateUrl: './ingest-run.component.html',
  imports: [RouterModule, FormsModule, SharedModule, SortDirective, SortByDirective, FormatMediumDatetimePipe],
})
export class IngestRunComponent implements OnInit {
  subscription: Subscription | null = null;
  ingestRuns = signal<IIngestRun[]>([]);
  isLoading = false;

  sortState = sortStateSignal({});

  public readonly router = inject(Router);
  protected readonly ingestRunService = inject(IngestRunService);
  protected readonly activatedRoute = inject(ActivatedRoute);
  protected readonly sortService = inject(SortService);
  protected modalService = inject(NgbModal);
  protected ngZone = inject(NgZone);

  trackId = (item: IIngestRun): number => this.ingestRunService.getIngestRunIdentifier(item);

  ngOnInit(): void {
    this.subscription = combineLatest([this.activatedRoute.queryParamMap, this.activatedRoute.data])
      .pipe(
        tap(([params, data]) => this.fillComponentAttributeFromRoute(params, data)),
        tap(() => {
          if (this.ingestRuns().length === 0) {
            this.load();
          } else {
            this.ingestRuns.set(this.refineData(this.ingestRuns()));
          }
        }),
      )
      .subscribe();
  }

  delete(ingestRun: IIngestRun): void {
    const modalRef = this.modalService.open(IngestRunDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.ingestRun = ingestRun;
    // unsubscribe not needed because closed completes on modal close
    modalRef.closed
      .pipe(
        filter(reason => reason === ITEM_DELETED_EVENT),
        tap(() => this.load()),
      )
      .subscribe();
  }

  load(): void {
    this.queryBackend().subscribe({
      next: (res: EntityArrayResponseType) => {
        this.onResponseSuccess(res);
      },
    });
  }

  navigateToWithComponentValues(event: SortState): void {
    this.handleNavigation(event);
  }

  protected fillComponentAttributeFromRoute(params: ParamMap, data: Data): void {
    this.sortState.set(this.sortService.parseSortParam(params.get(SORT) ?? data[DEFAULT_SORT_DATA]));
  }

  protected onResponseSuccess(response: EntityArrayResponseType): void {
    const dataFromBody = this.fillComponentAttributesFromResponseBody(response.body);
    this.ingestRuns.set(this.refineData(dataFromBody));
  }

  protected refineData(data: IIngestRun[]): IIngestRun[] {
    const { predicate, order } = this.sortState();
    return predicate && order ? data.sort(this.sortService.startSort({ predicate, order })) : data;
  }

  protected fillComponentAttributesFromResponseBody(data: IIngestRun[] | null): IIngestRun[] {
    return data ?? [];
  }

  protected queryBackend(): Observable<EntityArrayResponseType> {
    this.isLoading = true;
    const queryObject: any = {
      sort: this.sortService.buildSortParam(this.sortState()),
    };
    return this.ingestRunService.query(queryObject).pipe(tap(() => (this.isLoading = false)));
  }

  protected handleNavigation(sortState: SortState): void {
    const queryParamsObj = {
      sort: this.sortService.buildSortParam(sortState),
    };

    this.ngZone.run(() => {
      this.router.navigate(['./'], {
        relativeTo: this.activatedRoute,
        queryParams: queryParamsObj,
      });
    });
  }
}

<div>
  <h2 id="page-heading" data-cy="IngestRunHeading">
    <span jhiTranslate="booksEtlApp.ingestRun.home.title">Ingest Runs</span>

    <div class="d-flex justify-content-end">
      <button class="btn btn-info me-2" (click)="load()" [disabled]="isLoading">
        <fa-icon icon="sync" [animation]="isLoading ? 'spin' : undefined"></fa-icon>
        <span jhiTranslate="booksEtlApp.ingestRun.home.refreshListLabel">Refresh list</span>
      </button>

      <button
        id="jh-create-entity"
        data-cy="entityCreateButton"
        class="btn btn-primary jh-create-entity create-ingest-run"
        [routerLink]="['/ingest-run/new']"
      >
        <fa-icon icon="plus"></fa-icon>
        <span jhiTranslate="booksEtlApp.ingestRun.home.createLabel">Create a new Ingest Run</span>
      </button>
    </div>
  </h2>

  <jhi-alert-error />

  <jhi-alert />

  @if (ingestRuns().length === 0) {
    <div class="alert alert-warning" id="no-result">
      <span jhiTranslate="booksEtlApp.ingestRun.home.notFound">No Ingest Runs found</span>
    </div>
  } @else {
    <div class="table-responsive table-entities" id="entities">
      <table class="table table-striped" aria-describedby="page-heading">
        <thead>
          <tr jhiSort [(sortState)]="sortState" (sortChange)="navigateToWithComponentValues($event)">
            <th scope="col" jhiSortBy="id">
              <div class="d-flex">
                <span jhiTranslate="global.field.id">ID</span>

                <fa-icon class="p-1" icon="sort"></fa-icon>
              </div>
            </th>
            <th scope="col" jhiSortBy="startedAt">
              <div class="d-flex">
                <span jhiTranslate="booksEtlApp.ingestRun.startedAt">Started At</span>

                <fa-icon class="p-1" icon="sort"></fa-icon>
              </div>
            </th>
            <th scope="col" jhiSortBy="finishedAt">
              <div class="d-flex">
                <span jhiTranslate="booksEtlApp.ingestRun.finishedAt">Finished At</span>

                <fa-icon class="p-1" icon="sort"></fa-icon>
              </div>
            </th>
            <th scope="col" jhiSortBy="status">
              <div class="d-flex">
                <span jhiTranslate="booksEtlApp.ingestRun.status">Status</span>

                <fa-icon class="p-1" icon="sort"></fa-icon>
              </div>
            </th>
            <th scope="col" jhiSortBy="filesSeen">
              <div class="d-flex">
                <span jhiTranslate="booksEtlApp.ingestRun.filesSeen">Files Seen</span>

                <fa-icon class="p-1" icon="sort"></fa-icon>
              </div>
            </th>
            <th scope="col" jhiSortBy="filesParsed">
              <div class="d-flex">
                <span jhiTranslate="booksEtlApp.ingestRun.filesParsed">Files Parsed</span>

                <fa-icon class="p-1" icon="sort"></fa-icon>
              </div>
            </th>
            <th scope="col" jhiSortBy="filesFailed">
              <div class="d-flex">
                <span jhiTranslate="booksEtlApp.ingestRun.filesFailed">Files Failed</span>

                <fa-icon class="p-1" icon="sort"></fa-icon>
              </div>
            </th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
          @for (ingestRun of ingestRuns(); track trackId(ingestRun)) {
            <tr data-cy="entityTable">
              <td>
                <a [routerLink]="['/ingest-run', ingestRun.id, 'view']">{{ ingestRun.id }}</a>
              </td>
              <td>{{ ingestRun.startedAt | formatMediumDatetime }}</td>
              <td>{{ ingestRun.finishedAt | formatMediumDatetime }}</td>
              <td>{{ ingestRun.status }}</td>
              <td>{{ ingestRun.filesSeen }}</td>
              <td>{{ ingestRun.filesParsed }}</td>
              <td>{{ ingestRun.filesFailed }}</td>
              <td class="text-end">
                <div class="btn-group">
                  <a [routerLink]="['/ingest-run', ingestRun.id, 'view']" class="btn btn-info btn-sm" data-cy="entityDetailsButton">
                    <fa-icon icon="eye"></fa-icon>
                    <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
                  </a>

                  <a [routerLink]="['/ingest-run', ingestRun.id, 'edit']" class="btn btn-primary btn-sm" data-cy="entityEditButton">
                    <fa-icon icon="pencil-alt"></fa-icon>
                    <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
                  </a>

                  <button type="submit" (click)="delete(ingestRun)" class="btn btn-danger btn-sm" data-cy="entityDeleteButton">
                    <fa-icon icon="times"></fa-icon>
                    <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
                  </button>
                </div>
              </td>
            </tr>
          }
        </tbody>
      </table>
    </div>
  }
</div>

// src/main/webapp/app/entities/ingest-run/ingest-run.tsx
import React, { useEffect, useState } from 'react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { Button, Table } from 'reactstrap';
import { TextFormat, Translate, getSortState } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faSort, faSortDown, faSortUp } from '@fortawesome/free-solid-svg-icons';
import { APP_DATE_FORMAT } from 'app/config/constants';
import { ASC, DESC } from 'app/shared/util/pagination.constants';
import { overrideSortStateWithQueryParams } from 'app/shared/util/entity-utils';
import { useAppDispatch, useAppSelector } from 'app/config/store';

import { getEntities } from './ingest-run.reducer';

export const IngestRun = () => {
  const dispatch = useAppDispatch();

  const pageLocation = useLocation();
  const navigate = useNavigate();

  const [sortState, setSortState] = useState(overrideSortStateWithQueryParams(getSortState(pageLocation, 'id'), pageLocation.search));

  const ingestRunList = useAppSelector(state => state.ingestRun.entities);
  const loading = useAppSelector(state => state.ingestRun.loading);

  const getAllEntities = () => {
    dispatch(
      getEntities({
        sort: `${sortState.sort},${sortState.order}`,
      }),
    );
  };

  const sortEntities = () => {
    getAllEntities();
    const endURL = `?sort=${sortState.sort},${sortState.order}`;
    if (pageLocation.search !== endURL) {
      navigate(`${pageLocation.pathname}${endURL}`);
    }
  };

  useEffect(() => {
    sortEntities();
  }, [sortState.order, sortState.sort]);

  const sort = p => () => {
    setSortState({
      ...sortState,
      order: sortState.order === ASC ? DESC : ASC,
      sort: p,
    });
  };

  const handleSyncList = () => {
    sortEntities();
  };

  const getSortIconByFieldName = (fieldName: string) => {
    const sortFieldName = sortState.sort;
    const order = sortState.order;
    if (sortFieldName !== fieldName) {
      return faSort;
    }
    return order === ASC ? faSortUp : faSortDown;
  };

  return (
    <div>
      <h2 id="ingest-run-heading" data-cy="IngestRunHeading">
        <Translate contentKey="booksEtlApp.ingestRun.home.title">Ingest Runs</Translate>
        <div className="d-flex justify-content-end">
          <Button className="me-2" color="info" onClick={handleSyncList} disabled={loading}>
            <FontAwesomeIcon icon="sync" spin={loading} />{' '}
            <Translate contentKey="booksEtlApp.ingestRun.home.refreshListLabel">Refresh List</Translate>
          </Button>
          <Link to="/ingest-run/new" className="btn btn-primary jh-create-entity" id="jh-create-entity" data-cy="entityCreateButton">
            <FontAwesomeIcon icon="plus" />
            &nbsp;
            <Translate contentKey="booksEtlApp.ingestRun.home.createLabel">Create new Ingest Run</Translate>
          </Link>
        </div>
      </h2>
      <div className="table-responsive">
        {ingestRunList && ingestRunList.length > 0 ? (
          <Table responsive>
            <thead>
              <tr>
                <th className="hand" onClick={sort('id')}>
                  <Translate contentKey="booksEtlApp.ingestRun.id">ID</Translate> <FontAwesomeIcon icon={getSortIconByFieldName('id')} />
                </th>
                <th className="hand" onClick={sort('startedAt')}>
                  <Translate contentKey="booksEtlApp.ingestRun.startedAt">Started At</Translate>{' '}
                  <FontAwesomeIcon icon={getSortIconByFieldName('startedAt')} />
                </th>
                <th className="hand" onClick={sort('finishedAt')}>
                  <Translate contentKey="booksEtlApp.ingestRun.finishedAt">Finished At</Translate>{' '}
                  <FontAwesomeIcon icon={getSortIconByFieldName('finishedAt')} />
                </th>
                <th className="hand" onClick={sort('status')}>
                  <Translate contentKey="booksEtlApp.ingestRun.status">Status</Translate>{' '}
                  <FontAwesomeIcon icon={getSortIconByFieldName('status')} />
                </th>
                <th className="hand" onClick={sort('filesSeen')}>
                  <Translate contentKey="booksEtlApp.ingestRun.filesSeen">Files Seen</Translate>{' '}
                  <FontAwesomeIcon icon={getSortIconByFieldName('filesSeen')} />
                </th>
                <th className="hand" onClick={sort('filesParsed')}>
                  <Translate contentKey="booksEtlApp.ingestRun.filesParsed">Files Parsed</Translate>{' '}
                  <FontAwesomeIcon icon={getSortIconByFieldName('filesParsed')} />
                </th>
                <th className="hand" onClick={sort('filesFailed')}>
                  <Translate contentKey="booksEtlApp.ingestRun.filesFailed">Files Failed</Translate>{' '}
                  <FontAwesomeIcon icon={getSortIconByFieldName('filesFailed')} />
                </th>
                <th />
              </tr>
            </thead>
            <tbody>
              {ingestRunList.map((ingestRun, i) => (
                <tr key={`entity-${i}`} data-cy="entityTable">
                  <td>
                    <Button tag={Link} to={`/ingest-run/${ingestRun.id}`} color="link" size="sm">
                      {ingestRun.id}
                    </Button>
                  </td>
                  <td>{ingestRun.startedAt ? <TextFormat type="date" value={ingestRun.startedAt} format={APP_DATE_FORMAT} /> : null}</td>
                  <td>{ingestRun.finishedAt ? <TextFormat type="date" value={ingestRun.finishedAt} format={APP_DATE_FORMAT} /> : null}</td>
                  <td>{ingestRun.status}</td>
                  <td>{ingestRun.filesSeen}</td>
                  <td>{ingestRun.filesParsed}</td>
                  <td>{ingestRun.filesFailed}</td>
                  <td className="text-end">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`/ingest-run/${ingestRun.id}`} color="info" size="sm" data-cy="entityDetailsButton">
                        <FontAwesomeIcon icon="eye" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.view">View</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`/ingest-run/${ingestRun.id}/edit`} color="primary" size="sm" data-cy="entityEditButton">
                        <FontAwesomeIcon icon="pencil-alt" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.edit">Edit</Translate>
                        </span>
                      </Button>
                      <Button
                        onClick={() => (window.location.href = `/ingest-run/${ingestRun.id}/delete`)}
                        color="danger"
                        size="sm"
                        data-cy="entityDeleteButton"
                      >
                        <FontAwesomeIcon icon="trash" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.delete">Delete</Translate>
                        </span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        ) : (
          !loading && (
            <div className="alert alert-warning">
              <Translate contentKey="booksEtlApp.ingestRun.home.notFound">No Ingest Runs found</Translate>
            </div>
          )
        )}
      </div>
    </div>
  );
};

export default IngestRun;
