// src/main/webapp/app/entities/book-page-text/book-page-text-delete-dialog.tsx
import React, { useEffect, useState } from 'react';
import { useLocation, useNavigate, useParams } from 'react-router-dom';
import { Button, Modal, ModalBody, ModalFooter, ModalHeader } from 'reactstrap';
import { Translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { useAppDispatch, useAppSelector } from 'app/config/store';
import { deleteEntity, getEntity } from './book-page-text.reducer';

export const BookPageTextDeleteDialog = () => {
  const dispatch = useAppDispatch();
  const pageLocation = useLocation();
  const navigate = useNavigate();
  const { id } = useParams<'id'>();

  const [loadModal, setLoadModal] = useState(false);

  useEffect(() => {
    dispatch(getEntity(id));
    setLoadModal(true);
  }, []);

  const bookPageTextEntity = useAppSelector(state => state.bookPageText.entity);
  const updateSuccess = useAppSelector(state => state.bookPageText.updateSuccess);

  const handleClose = () => {
    navigate(`/book-page-text${pageLocation.search}`);
  };

  useEffect(() => {
    if (updateSuccess && loadModal) {
      handleClose();
      setLoadModal(false);
    }
  }, [updateSuccess]);

  const confirmDelete = () => {
    dispatch(deleteEntity(bookPageTextEntity.id));
  };

  return (
    <Modal isOpen toggle={handleClose}>
      <ModalHeader toggle={handleClose} data-cy="bookPageTextDeleteDialogHeading">
        <Translate contentKey="entity.delete.title">Confirm delete operation</Translate>
      </ModalHeader>
      <ModalBody id="booksEtlApp.bookPageText.delete.question">
        <Translate contentKey="booksEtlApp.bookPageText.delete.question" interpolate={{ id: bookPageTextEntity.id }}>
          Are you sure you want to delete this BookPageText?
        </Translate>
      </ModalBody>
      <ModalFooter>
        <Button color="secondary" onClick={handleClose}>
          <FontAwesomeIcon icon="ban" />
          &nbsp;
          <Translate contentKey="entity.action.cancel">Cancel</Translate>
        </Button>
        <Button id="jhi-confirm-delete-bookPageText" data-cy="entityConfirmDeleteButton" color="danger" onClick={confirmDelete}>
          <FontAwesomeIcon icon="trash" />
          &nbsp;
          <Translate contentKey="entity.action.delete">Delete</Translate>
        </Button>
      </ModalFooter>
    </Modal>
  );
};

export default BookPageTextDeleteDialog;

// src/main/webapp/app/entities/book-page-text/delete/book-page-text-delete-dialog.component.ts
import { Component, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { NgbActiveModal } from '@ng-bootstrap/ng-bootstrap';

import SharedModule from 'app/shared/shared.module';
import { ITEM_DELETED_EVENT } from 'app/config/navigation.constants';
import { IBookPageText } from '../book-page-text.model';
import { BookPageTextService } from '../service/book-page-text.service';

@Component({
  templateUrl: './book-page-text-delete-dialog.component.html',
  imports: [SharedModule, FormsModule],
})
export class BookPageTextDeleteDialogComponent {
  bookPageText?: IBookPageText;

  protected bookPageTextService = inject(BookPageTextService);
  protected activeModal = inject(NgbActiveModal);

  cancel(): void {
    this.activeModal.dismiss();
  }

  confirmDelete(id: number): void {
    this.bookPageTextService.delete(id).subscribe(() => {
      this.activeModal.close(ITEM_DELETED_EVENT);
    });
  }
}

@if (bookPageText) {
  <form name="deleteForm" (ngSubmit)="confirmDelete(bookPageText.id!)">
    <div class="modal-header">
      <h4 class="modal-title" data-cy="bookPageTextDeleteDialogHeading" jhiTranslate="entity.delete.title">Confirm delete operation</h4>
    </div>

    <div class="modal-body">
      <jhi-alert-error />
      <p
        id="jhi-delete-bookPageText-heading"
        jhiTranslate="booksEtlApp.bookPageText.delete.question"
        [translateValues]="{ id: bookPageText.id }"
      >
        Are you sure you want to delete Book Page Text {{ bookPageText.id }}?
      </p>
    </div>

    <div class="modal-footer">
      <button type="button" class="btn btn-secondary" data-dismiss="modal" (click)="cancel()">
        <fa-icon icon="ban"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
      </button>

      <button id="jhi-confirm-delete-bookPageText" data-cy="entityConfirmDeleteButton" type="submit" class="btn btn-danger">
        <fa-icon icon="times"></fa-icon>&nbsp;<span jhiTranslate="entity.action.delete">Delete</span>
      </button>
    </div>
  </form>
}
