// src/main/webapp/app/entities/ingest-event/ingest-event-detail.tsx
import React, { useEffect } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Button, Col, Row } from 'reactstrap';
import { TextFormat, Translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { APP_DATE_FORMAT } from 'app/config/constants';
import { useAppDispatch, useAppSelector } from 'app/config/store';

import { getEntity } from './ingest-event.reducer';

export const IngestEventDetail = () => {
  const dispatch = useAppDispatch();

  const { id } = useParams<'id'>();

  useEffect(() => {
    dispatch(getEntity(id));
  }, []);

  const ingestEventEntity = useAppSelector(state => state.ingestEvent.entity);
  return (
    <Row>
      <Col md="8">
        <h2 data-cy="ingestEventDetailsHeading">
          <Translate contentKey="booksEtlApp.ingestEvent.detail.title">IngestEvent</Translate>
        </h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="id">
              <Translate contentKey="global.field.id">ID</Translate>
            </span>
          </dt>
          <dd>{ingestEventEntity.id}</dd>
          <dt>
            <span id="runId">
              <Translate contentKey="booksEtlApp.ingestEvent.runId">Run Id</Translate>
            </span>
          </dt>
          <dd>{ingestEventEntity.runId}</dd>
          <dt>
            <span id="documentId">
              <Translate contentKey="booksEtlApp.ingestEvent.documentId">Document Id</Translate>
            </span>
          </dt>
          <dd>{ingestEventEntity.documentId}</dd>
          <dt>
            <span id="topic">
              <Translate contentKey="booksEtlApp.ingestEvent.topic">Topic</Translate>
            </span>
          </dt>
          <dd>{ingestEventEntity.topic}</dd>
          <dt>
            <span id="payload">
              <Translate contentKey="booksEtlApp.ingestEvent.payload">Payload</Translate>
            </span>
          </dt>
          <dd>{ingestEventEntity.payload}</dd>
          <dt>
            <span id="createdAt">
              <Translate contentKey="booksEtlApp.ingestEvent.createdAt">Created At</Translate>
            </span>
          </dt>
          <dd>
            {ingestEventEntity.createdAt ? <TextFormat value={ingestEventEntity.createdAt} type="date" format={APP_DATE_FORMAT} /> : null}
          </dd>
          <dt>
            <Translate contentKey="booksEtlApp.ingestEvent.ingestRun">Ingest Run</Translate>
          </dt>
          <dd>{ingestEventEntity.ingestRun ? ingestEventEntity.ingestRun.id : ''}</dd>
        </dl>
        <Button tag={Link} to="/ingest-event" replace color="info" data-cy="entityDetailsBackButton">
          <FontAwesomeIcon icon="arrow-left" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.back">Back</Translate>
          </span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/ingest-event/${ingestEventEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.edit">Edit</Translate>
          </span>
        </Button>
      </Col>
    </Row>
  );
};

export default IngestEventDetail;

// src/main/webapp/app/entities/ingest-event/detail/ingest-event-detail.component.ts
import { Component, inject, input } from '@angular/core';
import { RouterModule } from '@angular/router';

import SharedModule from 'app/shared/shared.module';
import { FormatMediumDatetimePipe } from 'app/shared/date';
import { DataUtils } from 'app/core/util/data-util.service';
import { IIngestEvent } from '../ingest-event.model';

@Component({
  selector: 'jhi-ingest-event-detail',
  templateUrl: './ingest-event-detail.component.html',
  imports: [SharedModule, RouterModule, FormatMediumDatetimePipe],
})
export class IngestEventDetailComponent {
  ingestEvent = input<IIngestEvent | null>(null);

  protected dataUtils = inject(DataUtils);

  byteSize(base64String: string): string {
    return this.dataUtils.byteSize(base64String);
  }

  openFile(base64String: string, contentType: string | null | undefined): void {
    this.dataUtils.openFile(base64String, contentType);
  }

  previousState(): void {
    window.history.back();
  }
}

<div class="d-flex justify-content-center">
  <div class="col-8">
    @if (ingestEvent(); as ingestEventRef) {
      <div>
        <h2 data-cy="ingestEventDetailsHeading"><span jhiTranslate="booksEtlApp.ingestEvent.detail.title">Ingest Event</span></h2>

        <hr />

        <jhi-alert-error />

        <jhi-alert />

        <dl class="row-md jh-entity-details">
          <dt><span jhiTranslate="global.field.id">ID</span></dt>
          <dd>
            <span>{{ ingestEventRef.id }}</span>
          </dd>
          <dt><span jhiTranslate="booksEtlApp.ingestEvent.runId">Run Id</span></dt>
          <dd>
            <span>{{ ingestEventRef.runId }}</span>
          </dd>
          <dt><span jhiTranslate="booksEtlApp.ingestEvent.documentId">Document Id</span></dt>
          <dd>
            <span>{{ ingestEventRef.documentId }}</span>
          </dd>
          <dt><span jhiTranslate="booksEtlApp.ingestEvent.topic">Topic</span></dt>
          <dd>
            <span>{{ ingestEventRef.topic }}</span>
          </dd>
          <dt><span jhiTranslate="booksEtlApp.ingestEvent.payload">Payload</span></dt>
          <dd>
            <span>{{ ingestEventRef.payload }}</span>
          </dd>
          <dt><span jhiTranslate="booksEtlApp.ingestEvent.createdAt">Created At</span></dt>
          <dd>
            <span>{{ ingestEventRef.createdAt | formatMediumDatetime }}</span>
          </dd>
          <dt><span jhiTranslate="booksEtlApp.ingestEvent.ingestRun">Ingest Run</span></dt>
          <dd>
            @if (ingestEvent()!.ingestRun) {
              <div>
                <a [routerLink]="['/ingest-run', ingestEvent()!.ingestRun?.id, 'view']">{{ ingestEventRef.ingestRun?.id }}</a>
              </div>
            }
          </dd>
        </dl>

        <button type="submit" (click)="previousState()" class="btn btn-info" data-cy="entityDetailsBackButton">
          <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back">Back</span>
        </button>

        <button type="button" [routerLink]="['/ingest-event', ingestEventRef.id, 'edit']" class="btn btn-primary">
          <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span jhiTranslate="entity.action.edit">Edit</span>
        </button>
      </div>
    }
  </div>
</div>
