// src/main/webapp/app/entities/book-page-text/book-page-text-detail.tsx
import React, { useEffect } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Button, Col, Row } from 'reactstrap';
import { Translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { useAppDispatch, useAppSelector } from 'app/config/store';

import { getEntity } from './book-page-text.reducer';

export const BookPageTextDetail = () => {
  const dispatch = useAppDispatch();

  const { id } = useParams<'id'>();

  useEffect(() => {
    dispatch(getEntity(id));
  }, []);

  const bookPageTextEntity = useAppSelector(state => state.bookPageText.entity);
  return (
    <Row>
      <Col md="8">
        <h2 data-cy="bookPageTextDetailsHeading">
          <Translate contentKey="booksEtlApp.bookPageText.detail.title">BookPageText</Translate>
        </h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="id">
              <Translate contentKey="global.field.id">ID</Translate>
            </span>
          </dt>
          <dd>{bookPageTextEntity.id}</dd>
          <dt>
            <span id="documentId">
              <Translate contentKey="booksEtlApp.bookPageText.documentId">Document Id</Translate>
            </span>
          </dt>
          <dd>{bookPageTextEntity.documentId}</dd>
          <dt>
            <span id="pageNo">
              <Translate contentKey="booksEtlApp.bookPageText.pageNo">Page No</Translate>
            </span>
          </dt>
          <dd>{bookPageTextEntity.pageNo}</dd>
          <dt>
            <span id="text">
              <Translate contentKey="booksEtlApp.bookPageText.text">Text</Translate>
            </span>
          </dt>
          <dd>{bookPageTextEntity.text}</dd>
          <dt>
            <Translate contentKey="booksEtlApp.bookPageText.book">Book</Translate>
          </dt>
          <dd>{bookPageTextEntity.book ? bookPageTextEntity.book.documentId : ''}</dd>
        </dl>
        <Button tag={Link} to="/book-page-text" replace color="info" data-cy="entityDetailsBackButton">
          <FontAwesomeIcon icon="arrow-left" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.back">Back</Translate>
          </span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/book-page-text/${bookPageTextEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.edit">Edit</Translate>
          </span>
        </Button>
      </Col>
    </Row>
  );
};

export default BookPageTextDetail;

// src/main/webapp/app/entities/book-page-text/detail/book-page-text-detail.component.ts
import { Component, inject, input } from '@angular/core';
import { RouterModule } from '@angular/router';

import SharedModule from 'app/shared/shared.module';
import { DataUtils } from 'app/core/util/data-util.service';
import { IBookPageText } from '../book-page-text.model';

@Component({
  selector: 'jhi-book-page-text-detail',
  templateUrl: './book-page-text-detail.component.html',
  imports: [SharedModule, RouterModule],
})
export class BookPageTextDetailComponent {
  bookPageText = input<IBookPageText | null>(null);

  protected dataUtils = inject(DataUtils);

  byteSize(base64String: string): string {
    return this.dataUtils.byteSize(base64String);
  }

  openFile(base64String: string, contentType: string | null | undefined): void {
    this.dataUtils.openFile(base64String, contentType);
  }

  previousState(): void {
    window.history.back();
  }
}

<div class="d-flex justify-content-center">
  <div class="col-8">
    @if (bookPageText(); as bookPageTextRef) {
      <div>
        <h2 data-cy="bookPageTextDetailsHeading"><span jhiTranslate="booksEtlApp.bookPageText.detail.title">Book Page Text</span></h2>

        <hr />

        <jhi-alert-error />

        <jhi-alert />

        <dl class="row-md jh-entity-details">
          <dt><span jhiTranslate="global.field.id">ID</span></dt>
          <dd>
            <span>{{ bookPageTextRef.id }}</span>
          </dd>
          <dt><span jhiTranslate="booksEtlApp.bookPageText.documentId">Document Id</span></dt>
          <dd>
            <span>{{ bookPageTextRef.documentId }}</span>
          </dd>
          <dt><span jhiTranslate="booksEtlApp.bookPageText.pageNo">Page No</span></dt>
          <dd>
            <span>{{ bookPageTextRef.pageNo }}</span>
          </dd>
          <dt><span jhiTranslate="booksEtlApp.bookPageText.text">Text</span></dt>
          <dd>
            <span>{{ bookPageTextRef.text }}</span>
          </dd>
          <dt><span jhiTranslate="booksEtlApp.bookPageText.book">Book</span></dt>
          <dd>
            @if (bookPageText()!.book) {
              <div>
                <a [routerLink]="['/book', bookPageText()!.book?.id, 'view']">{{ bookPageTextRef.book?.documentId }}</a>
              </div>
            }
          </dd>
        </dl>

        <button type="submit" (click)="previousState()" class="btn btn-info" data-cy="entityDetailsBackButton">
          <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back">Back</span>
        </button>

        <button type="button" [routerLink]="['/book-page-text', bookPageTextRef.id, 'edit']" class="btn btn-primary">
          <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span jhiTranslate="entity.action.edit">Edit</span>
        </button>
      </div>
    }
  </div>
</div>
